# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from shapely.geometry import LineString, Polygon
from shapely.ops import polygonize, unary_union
from typing import Any
import ezdxf
import math
import os
import pandas
import traceback

def run_task(params: Any, LOG: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ezdxf
import math
import os
import traceback
import pandas
import shapely
import shapely.geometry
import shapely.geometry.LineString
import shapely.geometry.Polygon
import shapely.ops