# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from shapely.geometry import LineString, MultiLineString
from shapely.ops import linemerge, unary_union
from typing import Any
import ezdxf
import os
import traceback

def entity_to_linestring(e: Any) -> Any:
    ...

def get_y_at_x(line: Any, x: Any) -> Any:
    ...

def run_task(params: Any, LOG: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ezdxf
import os
import traceback
import shapely
import shapely.geometry
import shapely.geometry.LineString
import shapely.geometry.MultiLineString
import shapely.ops