# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import ezdxf
import os
import re
import traceback

def get_best_pt(e: Any) -> Any:
    ...

def get_txt(e: Any) -> Any:
    ...

def run_task(params: Any, LOG: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ezdxf
import re
import os
import traceback