# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import Counter, defaultdict
from shapely.geometry import LineString, Point, Polygon, box
from shapely.ops import linemerge, polygonize, unary_union
from typing import Any
import ezdxf
import math
import os
import pandas
import re
import traceback

def get_lines_raw(msp: Any, layer: Any) -> Any:
    ...

def extend_line_simple(line: Any, dist: Any) -> Any:
    ...

def build_final_poly(lines: Any, ground_poly: Any, top_y: Any) -> Any:
    ...

def station_sort_key(station_str: Any) -> Any:
    ...

def add_hatch_and_text(msp: Any, poly: Any, color: Any, layer: Any, text_height: Any) -> Any:
    ...

def run_task(params: Any, LOG: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ezdxf
import pandas
import os
import math
import re
import traceback
import shapely
import shapely.geometry
import shapely.geometry.LineString
import shapely.geometry.Point
import shapely.geometry.box
import shapely.geometry.Polygon
import shapely.ops
import collections
import collections.defaultdict
import collections.Counter